baseurl: "https://profepaiche.com"
languageCode: "en-us"
title: "Profesor Paiche"
footnotereturnlinkcontents: "↩"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Posts
      url: "posts/"
      weight: 5
    # - name: Notes
    #   url: "notes/"
    #   weight: 6

params:
  description: "A simple and minimal personal blog where I share the stuff I do."
  footer: "Dante Castro - {Year} | [Github](https://github.com/profesorpaiche)"
